"""Contas e Usuarios

Revision ID: bdf6d715a171
Revises: 
Create Date: 2023-06-18 10:32:44.780487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdf6d715a171'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=30), nullable=True),
    sa.Column('numero', sa.Integer(), nullable=True),
    sa.Column('salario', sa.Numeric(), nullable=True),
    sa.Column('email', sa.String(length=30), nullable=True),
    sa.Column('senha', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuarios')
    # ### end Alembic commands ###
